import = [
  "~/dots/alacritty/.config/alacritty/themes/themes/rose-pine.toml"
]
live_config_reload = true

[font]
size = 10

[font.normal]
family = "JetBrains Mono Nerd Font"

[window]
opacity = 1
blur = true
decorations = "None"

  [window.padding]
  x = 10
  y = 10

[cursor]
blink_interval = 1_000

  [cursor.style]
  blinking = "Always"

[mouse]
hide_when_typing = true

[scrolling]
history = 3_000
