import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

[font]
size = 10

[font.normal]
family = "JetBrains Mono Nerd Font" 

[window]
opacity = 0.9
blur = true
decorations = "None"

[window.padding]
x = 10
y = 10

[cursor.style]
blinking = "Always"

[cursor]
blink_interval = 1000

[mouse]
hide_when_typing = true

[scrolling]
history = 3000
