set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-256color:Tc,*:Ss=\E[%p1%d q:Se=\E[ q' # fix for non blinking cursor in tmux sessions

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

set -g base-index 1  

set -g status-style 'bg=default fg=#5eacd3'
set -g status-left ''
set -g status-right ' %H:%M '
set -g status-justify left
set -g status-position top

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @catppuccin_status_background 'none'


# clears term screen
bind r send-keys -R \; clear-history \; send-keys C-l

# set vi-mode
set-window-option -g mode-keys vi

# set fish as default shell
set-option -g default-shell /usr/bin/fish
set-option -g default-command /usr/bin/fish

# bash script used for creating new tmux sessions / execute by pressing prefix key + f
bind-key f run-shell "tmux neww ~/scripts/tmux-sessionizer" 

# creates new tmux window
bind -r n new-window

# deletes current window
bind q kill-pane

# switch between tmux windows with Ctrl+[ and Ctrl+]
bind -n C-] next-window
bind -n C-[ previous-window

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
run '~/.tmux/plugins/tpm/catppuccin.tmux'
